/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.event.KeyEvent;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.UIManager;
import com.jtattoo.plaf.smart.*;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Laptop
 */
public class Vista extends javax.swing.JFrame {

    /**
     * Creates new form Vista
     */
    int logs = 0, view = 0;
    DefaultListModel modeloList = new DefaultListModel();
    int cont = 1;

    public Vista() {
        initComponents();
        setTitle("JCompiler");
        setIconImage(new ImageIcon(getClass().getResource("/Images/Code_96px.png")).getImage());
        ((JPanel) getContentPane()).setOpaque(false);
        jTabbedPane1.setVisible(false);
        txtSource.setFont(new java.awt.Font("Dialog", 0, 15));
        txtSource.setSelectionColor(new java.awt.Color(51, 204, 0));
        txtSource.setLineWrap(true);
        txtSource.setWrapStyleWord(true);
        listnumeros.setModel(modeloList);
        modeloList.addElement(1);
        txtCompilacion.setEditable(false);
        txtResultados.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        listnumeros = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtSource = new javax.swing.JTextArea();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtCompilacion = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtResultados = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setBackground(new java.awt.Color(204, 204, 204));
        jToolBar1.setRollover(true);

        jButton3.setBackground(new java.awt.Color(204, 204, 204));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Settings_20px.png"))); // NOI18N
        jButton3.setToolTipText("Compilar");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton3);

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Command Line_20px.png"))); // NOI18N
        jButton1.setToolTipText("ver salida");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jButton4.setBackground(new java.awt.Color(204, 204, 204));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Eye_20px.png"))); // NOI18N
        jButton4.setToolTipText("cambiar tema");
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton4);

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Shutdown_20px.png"))); // NOI18N
        jButton2.setToolTipText("salir");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setMaximumSize(new java.awt.Dimension(32, 32));
        jButton2.setMinimumSize(new java.awt.Dimension(32, 32));
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);

        jScrollPane1.setViewportView(listnumeros);

        jSplitPane1.setLeftComponent(jScrollPane1);

        txtSource.setColumns(20);
        txtSource.setRows(5);
        txtSource.setCaretColor(new java.awt.Color(51, 51, 51));
        txtSource.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSourceKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(txtSource);

        jSplitPane1.setRightComponent(jScrollPane2);

        jTabbedPane1.setBackground(new java.awt.Color(204, 204, 204));
        jTabbedPane1.setToolTipText("");

        txtCompilacion.setColumns(20);
        txtCompilacion.setRows(5);
        jScrollPane3.setViewportView(txtCompilacion);

        jTabbedPane1.addTab("Compilación", jScrollPane3);

        txtResultados.setColumns(20);
        txtResultados.setRows(5);
        jScrollPane4.setViewportView(txtResultados);

        jTabbedPane1.addTab("Resultados", jScrollPane4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 711, Short.MAX_VALUE)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Compilación");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (logs == 0) {
            logs = 1;
            jTabbedPane1.setVisible(true);
        } else {
            jTabbedPane1.setVisible(false);
            logs = 0;
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        logs = 1;
        jTabbedPane1.setVisible(true);
        txtCompilacion.setText("Tokens:\n");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if (view == 0) {
            listnumeros.setBackground(new java.awt.Color(51, 51, 51));
            listnumeros.setForeground(new java.awt.Color(255, 255, 255));
            txtSource.setBackground(new java.awt.Color(51, 51, 51));
            txtSource.setForeground(new java.awt.Color(255, 255, 255));
            txtSource.setCaretColor(new java.awt.Color(255, 255, 255));
            txtCompilacion.setBackground(new java.awt.Color(51, 51, 51));
            txtCompilacion.setForeground(new java.awt.Color(255, 255, 255));
            txtResultados.setBackground(new java.awt.Color(51, 51, 51));
            txtResultados.setForeground(new java.awt.Color(255, 255, 255));
            view = 1;
        } else {
            listnumeros.setBackground(new java.awt.Color(255, 255, 255));
            listnumeros.setForeground(new java.awt.Color(0, 0, 0));
            txtSource.setBackground(new java.awt.Color(255, 255, 255));
            txtSource.setForeground(new java.awt.Color(0, 0, 0));
            txtSource.setCaretColor(new java.awt.Color(0, 0, 0));
            txtCompilacion.setBackground(new java.awt.Color(255, 255, 255));
            txtCompilacion.setForeground(new java.awt.Color(0, 0, 0));
            txtResultados.setBackground(new java.awt.Color(255, 255, 255));
            txtResultados.setForeground(new java.awt.Color(0, 0, 0));
            view = 0;
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtSourceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSourceKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER || evt.getKeyCode() == KeyEvent.VK_BACK_SPACE) {
            modeloList.removeAllElements();
            for (int i = 0; i < contarlineas(); i++) {
                modeloList.addElement(i + 1);
            }
        }
    }//GEN-LAST:event_txtSourceKeyPressed

    private int contarlineas() {
        int contsaltos = 0;
        for (int i = 0; i < txtSource.getText().length(); i++) {
            if (txtSource.getText().charAt(i) == '\n') {
                contsaltos++;
            }
        }
        if (contsaltos == 0) {
            System.out.println("cantidad de lineas" + 1);
            return 1;
        }
        System.out.println("cantidad de lineas" + (contsaltos + 1));
        return contsaltos + 1;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            // select the Look and Feel
            UIManager.setLookAndFeel("com.jtattoo.plaf.aluminium.AluminiumLookAndFeel");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Vista.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(Vista.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(Vista.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(Vista.class.getName()).log(Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JList<String> listnumeros;
    public javax.swing.JTextArea txtCompilacion;
    public javax.swing.JTextArea txtResultados;
    public javax.swing.JTextArea txtSource;
    // End of variables declaration//GEN-END:variables
}
